pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  batch: true
  branches:
    include: 
    - refs/heads/*
  paths:
    include: 
    - parrot/

variables:
  projectName: parrot
  registryServerName: '$(registryName).azurecr.io'
  imageName: '$(projectName)'
  # define 3 more variables: registryName, registryLogin and registryPassword in the build pipeline in UI


steps:
- bash: docker build -f $(system.defaultWorkingDirectory)/$(projectName)/Dockerfile -t $(registryServerName)/$(imageName):$(build.buildId) $(system.defaultWorkingDirectory)/$(projectName)
  displayName: 'docker build'
